### ISSUE TITLE
New Line Stripping

### ISSUE THREAD

**Issue by tomcoady** [balthisar/tidy#4] opened 2018-12-03 14:50 UTC
When I insert a file with new lines the output shows these as removed.
I need to preserve new lines between quote marks to paste into a spreadsheet.

**Comment by balthisar** [comment] 2018-12-03 20:45
@tomcoady, can you describes some steps to reproduce this? Are you opening the file with file->open, or pasting text, or dragging and dropping it? Can you attach before and after files to this issue so that I know specifically the behavior that's not correct?

Thanks.

**Comment by balthisar** [comment] 2021-04-27 19:16
I'll close this due to no answer. @tomcoady, feel free to re-open this if you're still around.

**Closed as completed by balthisar** 2021-04-27 19:16 UTC
